# Generated by Django 4.0.2 on 2024-11-24 15:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('servicios', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TipoEvento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombreevento', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Evento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descripcion', models.TextField()),
                ('valor_referencial', models.DecimalField(decimal_places=2, max_digits=10)),
                ('numero_horas_permitidas', models.PositiveIntegerField()),
                ('valor_extra_hora', models.DecimalField(decimal_places=2, max_digits=10)),
                ('tipo_evento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='servicios.tipoevento')),
            ],
        ),
    ]
