# Generated by Django 4.0.2 on 2024-11-24 01:40

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Alquiler',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_alquiler', models.DateField()),
                ('hora_inicio_reserva', models.TimeField()),
                ('hora_fin_planificada_reserva', models.TimeField()),
                ('hora_fin_real_reserva', models.TimeField(blank=True, null=True)),
                ('costo_alquiler', models.DecimalField(decimal_places=2, max_digits=10)),
                ('calificacion_cliente', models.IntegerField(blank=True, null=True)),
                ('calificacion_negocio', models.IntegerField(blank=True, null=True)),
                ('observacion', models.TextField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='Servicio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descripcion', models.CharField(max_length=100)),
                ('valor_por_unidad', models.DecimalField(decimal_places=2, max_digits=10)),
            ],
        ),
        migrations.CreateModel(
            name='TipoEvento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombreevento', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Evento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descripcion', models.TextField()),
                ('valor_referencial', models.DecimalField(decimal_places=2, max_digits=10)),
                ('numero_horas_permitidas', models.PositiveIntegerField()),
                ('valor_extra_hora', models.DecimalField(decimal_places=2, max_digits=10)),
                ('tipo_evento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tinocoloco_app.tipoevento')),
            ],
        ),
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('identificacion', models.CharField(max_length=20)),
                ('nacionalidad', models.CharField(max_length=100)),
                ('telefono', models.CharField(max_length=20)),
                ('fecha_registro', models.DateTimeField(auto_now_add=True)),
                ('genero', models.CharField(choices=[('M', 'Masculino'), ('F', 'Femenino')], max_length=20)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='AlquilerServicio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad', models.PositiveIntegerField()),
                ('alquiler', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tinocoloco_app.alquiler')),
                ('servicio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tinocoloco_app.servicio')),
            ],
        ),
        migrations.AddField(
            model_name='alquiler',
            name='cliente',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tinocoloco_app.cliente'),
        ),
        migrations.AddField(
            model_name='alquiler',
            name='evento',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tinocoloco_app.evento'),
        ),
    ]
