# Generated by Django 4.0.2 on 2024-11-24 15:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tinocoloco_app', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='alquilerservicio',
            name='alquiler',
        ),
        migrations.RemoveField(
            model_name='alquilerservicio',
            name='servicio',
        ),
        migrations.RemoveField(
            model_name='evento',
            name='tipo_evento',
        ),
        migrations.DeleteModel(
            name='Alquiler',
        ),
        migrations.DeleteModel(
            name='AlquilerServicio',
        ),
        migrations.DeleteModel(
            name='Evento',
        ),
        migrations.DeleteModel(
            name='Servicio',
        ),
        migrations.DeleteModel(
            name='TipoEvento',
        ),
    ]
