# Generated by Django 4.0.2 on 2024-11-26 17:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tinocoloco_app', '0003_emailconfirmationtoken'),
    ]

    operations = [
        migrations.DeleteModel(
            name='EmailConfirmationToken',
        ),
    ]
