# Generated by Django 4.0.2 on 2024-11-24 15:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tinocoloco_app', '0002_remove_alquilerservicio_alquiler_and_more'),
        ('servicios', '0002_tipoevento_evento'),
        ('reservaciones', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Alquiler',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_alquiler', models.DateField()),
                ('hora_inicio_reserva', models.TimeField()),
                ('hora_fin_planificada_reserva', models.TimeField()),
                ('hora_fin_real_reserva', models.TimeField(blank=True, null=True)),
                ('costo_alquiler', models.DecimalField(decimal_places=2, max_digits=10)),
                ('calificacion_cliente', models.IntegerField(blank=True, null=True)),
                ('calificacion_negocio', models.IntegerField(blank=True, null=True)),
                ('observacion', models.TextField(blank=True)),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tinocoloco_app.cliente')),
                ('evento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='servicios.evento')),
            ],
        ),
        migrations.CreateModel(
            name='AlquilerServicio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad', models.PositiveIntegerField()),
                ('alquiler', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='reservaciones.alquiler')),
                ('servicio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='servicios.servicio')),
            ],
        ),
    ]
